# Generated by Django 4.2.7 on 2023-11-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="chat_id",
            new_name="chat_id1",
        ),
    ]
